channels:
- conda-forge
dependencies:
- python=3.8.18
- pip<=23.3.1
- pip:
  - mlflow==2.9.2
  - cffi==1.16.0
  - cloudpickle==3.0.0
  - cytoolz==0.12.2
  - dask==2022.12.1
  - graphviz==0.20.1
  - jinja2==3.1.2
  - lightgbm==3.3.5
  - matplotlib==3.7.4
  - numpy==1.23.5
  - packaging==23.2
  - pandas==1.5.3
  - psutil==5.9.0
  - pyarrow==14.0.2
  - pyyaml==6.0.1
  - scikit-learn==1.2.2
  - scipy==1.10.1
name: mlflow-env
